export interface School {
    id: string | number;
    name: string;
}

export interface College {
    collegeNo: string;
    collegeName: string;
}

export interface Campus {
    /** 校区编号 */
    campusId: string;
    /** 校区名字 */
    campusName: string;
    /** 校区所在区域id */
    campusAid: number;
    /** 校区所在区域 */
    campusAreaName: string;
    /** 校区所在市id */
    campusCid: number;
    /** 校区所在市 */
    campusCityName: string;
    /** 校区所在省份id */
    campusPid: number;
    /** 校区所在省份 */
    campusProvinceName: string;
}

/**
 * 变更消费者信息
 */
export interface ChangeConsumerVerifyReq {
    /** 入学年份 */
    enterSchoolYear: number;
    /** 学校编号 */
    schoolId: string;
    /** 学院编号 */
    collegeNo: string;
    /**校区名称(v265) */
    campusName: string;
    /** 学院名称 */
    collegeName: string;
    /** 学院类型,0已存在学院编号,1使用自定义学院名称	 */
    collegeType: number;
    /** 校区类型,0已存在校区编号,1使用自定义校区名称 */
    campusType: number;
    /** 校区编号(v265) */
    campusId: string;
    /** 年制 */
    maxGrade: number;
    /** 区域编号(v265) */
    campusAid: number | string;
    /** 学生证明图片 */
    images: any[];
}

/**
 * 提交消费者认证信息
 */
export interface SubmitConsumerVerifyReq {
    schoolId: number;
    realName: string;
    idNumber: string;
    images: any[];
    verifyType: number;
    campusName: string | number;
    campusId: string;
    campusType: number;
}

export interface Treatment {
    treatmentId: string;
    title: string;
    logoImage: string;
    contentImage: string;
}

/**
 * 返回结果
 */
export interface StudentInfo {
    /** 学信网code(v265)*/
    chsiAuthCode?: string;
    /** 入学年份*/
    enterSchoolYear?: number;
    /** 学校编号*/
    schoolId?: number;
    /** 申请编辑信息状态,-2：未变更，-1：失败，0：待审核，1：通过(v265)*/
    changeVerifyStatus?: string;
    /** 学院编号*/
    collegeNo?: string;
    /** 已完成第三版学生认证, 1:是, 0:否*/
    v3Verified?: number;
    /** 校区名称(v265)*/
    campusName?: string;
    /** 省份编号(v265)*/
    campusPid?: string;
    /** 真实姓名*/
    realName?: string;
    /** 身份证号*/
    idNumber?: string;
    /** 2:通过,1:审核中,0:未提交,-1:失败(v265)*/
    consumerVerifyStatus?: number;
    /** 是否可提交审核, 1:是, 0:否*/
    canSubmitVerify?: number;
    /** 是否可以修改真实姓名, 1:是, 0:否*/
    realNameCanChange?: number;
    /** 学院名称*/
    collegeName?: string;
    /** 学生认证方式,1:原身份认证,2:学信网,3消费者身份证,4消费者绿色(v265)*/
    userAuthMethodType?: number;
    /** 学校名称*/
    schoolName?: string;
    /** 审核状态, 0:待审核, 1:审核通过, -1:审核不通过, -2:未提交审核*/
    verify?: number;
    /** 学生证明图片*/
    images?: string[];
    /** 学信网code(v265)*/
    campusProvinceName?: string;
    /** 校区编号(v265)*/
    campusId?: string;
    /** 年制*/
    maxGrade?: number;
    /** 区域编号(v265)*/
    campusAid?: string;
    /** 区域名称(v265)*/
    campusAreaName?: string;
    /** 市编号(v265)*/
    campusCid?: string;
    /** 市名称(v265)*/
    campusCityName?: string;
    /** 审核失败原因*/
    verifyFailReason?: string;
    studentChangeDTO?: StudentChangeInfo;
}
/**
 * 变更信息
 */
export interface StudentChangeInfo {
    /** 入学年份*/
    enterSchoolYear?: number;
    /** 学校编号*/
    schoolNameschoolId?: number;
    /** 学院编号*/
    collegeNo?: string;
    /** 校区名称(v265)*/
    campusName?: string;
    /** 省份编号(v265)*/
    campusPid?: string;
    /** 学院名称*/
    collegeName?: string;
    /** 学校名称*/
    schoolName?: string;
    /** 审核状态, 0:待审核, 1:审核通过, -1:审核不通过, -2:未提交审核*/
    verify?: number;
    /** 学生证明图片*/
    images?: string[];
    /** 学信网code(v265)*/
    campusProvinceName?: string;
    /** 校区编号(v265)*/
    campusNamecampusId?: string;
    /** 年制*/
    maxGrade?: number;
    /** 区域编号(v265)*/
    campusAid?: string;
    /** 区域名称(v265)*/
    campusAreaName?: string;
    /** 市编号(v265)*/
    campusCid?: string;
    /** 市名称(v265)*/
    campusCityName?: string;
    /** 审核失败原因*/
    verifyFailReason?: string;
}

// Generated by https://quicktype.io

export interface AddressItem {
    value: number;
    label: string;
    level: number;
    name?: string;
    children?: AddressItem[];
}

/**
 * 信息完善
 */
export interface UpdateStudentCampus {
    campusName: string;
    campusId: string;
    campusAid: string;
    campusType: number;
}

/**
 * 投诉反馈
 */
export interface Feedback {
    /** 类型, 0:通用投诉,1:商品,2:任务,3:校园实习生,4:兼职,5:实习,6:社区班级,7:学生认证,8:意见反馈 */
    type: number;
    /** 投诉目标的编号,type=(1商品编号,2任务编号,3:实习项目编号,4:兼职编号,5:实习编号,6:班级编号) */
    aimNo: string;
    /** 投诉内容 */
    content: string;
    /** 投诉图片 */
    images: string[];
}

export interface ChangeStudentInfo {
    schoolId: number;
    enterSchoolYear: string;
    maxGrade: string;
    collegeType: number;
    collegeNo: string;
    collegeName: string;
    images: string[];
    campusType: string;
    campusId: string;
    campusName: string;
    campusAid: string;
}
