/** 活动配置信息 */
export interface IConfigInfo {
    backgroundColor: string /** 背景色*/;
    coverImage: string /** 活动封面*/;
    notSelectNavigationColor: string /**导航栏颜色*/;
    ruleImagesList: Array<String> /**规则图片*/;
    selectNavigationColor: string /**导航栏选中颜色*/;
}

// Generated by https://quicktype.io

export interface ISummerGoodsListReq {
    scrollId: string;
    size: number;
    activityNo: string;
    keywords: string;
    sortField: string;
    sortType: string;
    timeIds?: string;
}

/** 专区列表传参 */

export interface IZoneReqParams {
    scrollId?: string;
    isPreview: number;
    studentShopId: string;
}

/** 专区分类列表传参 */

export interface IZoneCategoryReqParams {
    activityNo: string;
    zoneId: string;
}

/** 专区配置类型 */
export interface IZoneConfig {
    activityNo: string;
    configMaterialInfo: IConfigInfo;
    isOwnerStudentShop: number;
    list: IZoneList[];
    lotteryNo: string;
    ruleImagesList: Array<string>;
}

/** 专区列表类型 */

export interface IZoneList {
    activityNo: string;
    image: string;
    title: string;
    zoneId: string;
    zoneType: number;
    isActive: boolean;
}

/** 分类类型 */
export interface ICategory {
    list: ICategoryList[];
}
export interface ICategoryList {
    id: number;
    categoryId: string;
    zoneId: string;
    activityNo: string;
    zoneType: number;
    categoryName: string;
}

/** 专区商品传参 */
export interface IZoneGoodsParams {
    zoneId: string;
    categoryId: string;
    studentShopId: string;
}

/** 专区商品列表 */

export interface IZoneGoods {
    list: IZoneGoodsList[];
}
export interface IZoneGoodsList {
    actGoodsNo: string;
    goodsNo: string;
    goodsType: number;
    goodsCover: string;
    goodsTitle: string;
    goodsPrice: number;
    goodsCommissionRate: number;
    goodsPriceOrigin: number;
    vacationPrice: number;
    discount: number;
    platformStudentPriceStatus: number;
    zoneId: number;
}
